version: "3"
networks:
  loki:
services:
  loki:
    image: grafana/loki:v1.2.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
  grafana:
    image: grafana/grafana:6.5.2
    ports:
      - "3000:3000"
    networks:
      - loki
  fluentd:
    image: fluentd:v1.6.2-1.0
    environment:
      FLUENT_CONF: /fluentd/etc/fluent.conf
    networks:
      - loki
    volumes:
      - ./host_logs:/var/log
      - ./fluent.conf:/fluentd/etc/fluent.conf
      - ./plugin:/etc/fluent/plugin
  nginx:
    image: nginx:1.17.6
    volumes:
      - ./host_logs:/var/log/nginx
    ports:
      - "8080:80"
